# Generated by Django 2.2 on 2020-01-23 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='imagine',
            new_name='image',
        ),
    ]
